using System;
using FractalBltEncoder;

namespace FractalGnnRouter;

/// <summary>
/// A zero-allocation graph routing engine that maps variable-length patches 
/// to specific on-disk MoE experts.
/// </summary>
public static class GnnRouter
{
    private const int WindowSize = 8; // Receptive field

    /// <summary>
    /// Routes incoming latent patches to specific MoE experts by simulating a local graph window.
    /// Strictly zero-allocation and branchless/predictable in hot paths.
    /// </summary>
    /// <param name="patches">The input patches generated by the FractalBltEncoder.</param>
    /// <param name="registry">The pre-loaded static expert registry.</param>
    /// <param name="outputBuffer">A pre-allocated buffer for resulting route assignments.</param>
    /// <returns>The total number of route assignments written.</returns>
    public static unsafe int ComputeRoutes(
        ReadOnlySpan<PatchBoundary> patches, 
        ref ExpertRegistry registry, 
        Span<RouteAssignment> outputBuffer)
    {
        if (outputBuffer.Length < patches.Length)
        {
            throw new ArgumentException("Output buffer is too small to accommodate the incoming patches.");
        }

        int routeCount = 0;

        // Allocate a sliding window adjacency matrix on the stack ONCE.
        // Size: WindowSize * WindowSize floats (8*8 = 64 floats = 256 bytes)
        // This easily fits in CPU cache and stack space without GC allocation.
        float* adjacencyMatrix = stackalloc float[WindowSize * WindowSize];

        for (int i = 0; i < patches.Length; i++)
        {
            // Mock graph message passing: fill local adjacency matrix.
            // For a real GNN, this would compute dot products of patch embeddings.
            // Here, we simulate by relying on patch lengths and local neighbors.
            int neighborCount = Math.Min(WindowSize, patches.Length - i);
            for (int k = 0; k < neighborCount; k++)
            {
                for (int j = 0; j < neighborCount; j++)
                {
                    // Calculate a deterministic dummy interaction weight between patches
                    adjacencyMatrix[k * WindowSize + j] = (patches[i + k].Length + patches[i + j].PeakEntropy) * 0.1f;
                }
            }

            // Top-K expert selection (K=1 for simplicity in routing).
            // We iterate over the expert registry to find the highest dot product
            // between the aggregated adjacency "state" and the expert embeddings.
            
            float bestWeight = -float.MaxValue;
            ushort bestExpertId = 0;

            // Compute a dummy aggregated state for patch [i]
            float aggregatedState = adjacencyMatrix[0]; // just grab the self-attention node

            for (int e = 0; e < registry.ActiveCount; e++)
            {
                // Score = dot(state, expert_embedding)
                float score = aggregatedState * registry.Embeddings[e];

                // Branchless-friendly selection (or highly predictable in modern architectures)
                if (score > bestWeight)
                {
                    bestWeight = score;
                    bestExpertId = registry.ExpertIds[e];
                }
            }

            // Assign the winning route
            outputBuffer[routeCount++] = new RouteAssignment(i, bestExpertId, bestWeight);
        }

        return routeCount;
    }
}
