using System;
using System.Runtime.CompilerServices;
using FractalBltEncoder;

namespace FractalGnnRouter;

/// <summary>
/// A zero-allocation graph routing engine that maps variable-length patches 
/// to specific on-disk MoE experts.
/// </summary>
public static class GnnRouter
{
    private const int WindowSize = 8; // Receptive field

    /// <summary>
    /// Routes incoming latent patches to specific MoE experts using a 1-hop Graph Convolution.
    /// Strictly zero-allocation and branchless/predictable in hot paths.
    /// </summary>
    /// <param name="patches">The input patches generated by the FractalBltEncoder.</param>
    /// <param name="registry">The pre-loaded static expert registry.</param>
    /// <param name="outputBuffer">A pre-allocated buffer for resulting route assignments.</param>
    /// <returns>The total number of route assignments written.</returns>
    public static unsafe int ComputeRoutes(
        ReadOnlySpan<PatchBoundary> patches, 
        ref ExpertRegistry registry, 
        Span<RouteAssignment> outputBuffer)
    {
        if (outputBuffer.Length < patches.Length)
        {
            throw new ArgumentException("Output buffer is too small to accommodate the incoming patches.");
        }

        int routeCount = 0;

        // Allocate a sliding window adjacency matrix and feature vector on the stack ONCE.
        // Adjacency Matrix: 8x8 floats = 64 floats = 256 bytes.
        // Node Features (Length and PeakEntropy): 2 floats per node * 8 nodes = 16 floats = 64 bytes.
        // Updated States: 2 floats per node * 8 nodes = 16 floats = 64 bytes.
        float* adjacencyMatrix = stackalloc float[WindowSize * WindowSize];
        float* nodeFeatures = stackalloc float[WindowSize * 2];
        float* updatedStates = stackalloc float[WindowSize * 2];

        for (int i = 0; i < patches.Length; i++)
        {
            int neighborCount = Math.Min(WindowSize, patches.Length - i);

            // 1. Populate Node Features (Length and Entropy)
            for (int k = 0; k < neighborCount; k++)
            {
                nodeFeatures[k * 2 + 0] = patches[i + k].Length;
                nodeFeatures[k * 2 + 1] = patches[i + k].PeakEntropy;
                
                // Clear updated states
                updatedStates[k * 2 + 0] = 0f;
                updatedStates[k * 2 + 1] = 0f;
            }

            // 2. Build Adjacency Matrix (Similarity/RBF kernel)
            for (int k = 0; k < neighborCount; k++)
            {
                for (int j = 0; j < neighborCount; j++)
                {
                    if (k == j) 
                    {
                        adjacencyMatrix[k * WindowSize + j] = 1.0f; // Self-loop
                    }
                    else
                    {
                        // Calculate Euclidean distance between features
                        float dLength = nodeFeatures[k * 2 + 0] - nodeFeatures[j * 2 + 0];
                        float dEntropy = nodeFeatures[k * 2 + 1] - nodeFeatures[j * 2 + 1];
                        float distSq = (dLength * dLength) + (dEntropy * dEntropy);
                        
                        // RBF Similarity: exp(-gamma * distSq)
                        adjacencyMatrix[k * WindowSize + j] = MathF.Exp(-0.1f * distSq);
                    }
                }
            }

            // 3. Graph Convolution: H^(l+1) = A * H^(l)
            for (int k = 0; k < neighborCount; k++)
            {
                for (int j = 0; j < neighborCount; j++)
                {
                    float weight = adjacencyMatrix[k * WindowSize + j];
                    updatedStates[k * 2 + 0] += weight * nodeFeatures[j * 2 + 0];
                    updatedStates[k * 2 + 1] += weight * nodeFeatures[j * 2 + 1];
                }
            }

            // 4. Linear Projection & Top-K Expert Selection for the current patch (k=0)
            // We project the 2D updated state into a scalar (or compare it with 1D expert embeddings).
            float pooledState = (updatedStates[0] * 0.5f) + (updatedStates[1] * 0.5f); // Simple linear projection

            float bestWeight = -float.MaxValue;
            ushort bestExpertId = 0;

            for (int e = 0; e < registry.ActiveCount; e++)
            {
                // Score = dot(state, expert_embedding)
                float score = pooledState * registry.Embeddings[e];

                if (score > bestWeight)
                {
                    bestWeight = score;
                    bestExpertId = registry.ExpertIds[e];
                }
            }

            // Assign the winning route
            outputBuffer[routeCount++] = new RouteAssignment(i, bestExpertId, bestWeight);
        }

        return routeCount;
    }
}
